server:
  port: 7081


logging:
  level:
    learning: debug
  file:
    name: pdfront.log

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.170.74:3306/yangdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1hblsqt!
    hikari:
      max-lifetime: 500000
      minimum-idle: 3
      maximum-pool-size: 10
  resources:
    static-locations: classpath:/templates/